# fly.toml app configuration file generated for nlp-api on 2023-09-23T20:25:01+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nlp-api"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:full"

[build.args]
  BP_CPYTHON_VERSION = "3.9.17"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
